sudo: false
addons:
    apt:
      packages: 
      - tree
install:
  - mkdir tools && cd tools
  - pwd
  - wget -q "https://github.com/gohugoio/hugo/releases/download/v0.40.2/hugo_0.40.2_Linux-64bit.tar.gz" -O "hugo.tar.gz"
  - tar -xvzf hugo.tar.gz
  - cd ..
  
script:
  - tree -a
  - git clone --depth 1 https://github.com/kishaningithub/hugo-shopping-product-catalogue-simple.git exampleSite/themes/
  - ls tools
  - ./tools/hugo -v --source exampleSite
